jobs:
  build:
    docker:
      - image: circleci/php:7.2-node-browsers
    steps:
      - checkout
      - run: cd site && composer install && vendor/bin/security-checker security:check composer.lock
  deploy_production:
    docker:
      - image: benword/ubuntu18.04-ansible2.7.5-nvm-yarn:0.0.1
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "31:b8:b7:6b:9c:5f:51:b1:5c:2b:4f:29:6e:54:f6:20"
      - run: mkdir -p ~/.ssh && cp trellis/keys/circleci.pub ~/.ssh/id_rsa.pub
      - run: cd trellis && echo "${vault_pass}" > .vault_pass && ansible-playbook deploy.yml -e "site=pressbooks.org env=production"
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy_production:
          requires:
            - build
          filters:
            branches:
              only: master
