# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/production/vault.yml

wordpress_sites:
  pressbooks.org:
    site_hosts:
      - canonical: pressbooks.org
        redirects:
          - www.pressbooks.org
          - pressbooks.pub
          - www.pressbooks.pub
      - canonical: docs.pressbooks.org
      - canonical: discourse.pressbooks.org
    local_path: ../pressbooks.org # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:pressbooks/pressbooks.org.git # replace with your Git repo URL
    repo_subtree_path: pressbooks.org # relative path to your Bedrock/WP directory in your repo
    branch: master
    multisite:
      enabled: true
      subdomains: true
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: true
  pressbooks.education:
    site_hosts:
      - canonical: pressbooks.education
    local_path: ../pressbooks.education # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:pressbooks/pressbooks.org.git # replace with your Git repo URL
    repo_subtree_path: pressbooks.education # relative path to your Bedrock/WP directory in your repo
    branch: master
    multisite:
      enabled: true
    ssl:
      enabled: true
      provider: letsencrypt
      hsts_include_subdomains: false
    cache:
      enabled: true
