# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/production/vault.yml

wordpress_sites:
  pressbooks.org:
    site_hosts:
      - canonical: pressbooks.org
        redirects:
          - www.pressbooks.org
          - pressbooks.pub
          - www.pressbooks.pub
          - pressbooks.dev
          - www.pressbooks.dev
      - canonical: docs.pressbooks.org
      - canonical: discourse.pressbooks.org
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:pressbooks/pressbooks.org.git # replace with your Git repo URL
    repo_subtree_path: site # relative path to your Bedrock/WP directory in your repo
    branch: master
    multisite:
      enabled: true
      subdomains: true
      cron: true
    ssl:
      enabled: true
      provider: manual
      cert: ~/certificates/pressbooks.org.20220126.fullchain.pem
      key: ~/certificates/pressbooks.org.20220126.privkey.pem
    cache:
      enabled: true
    env:
      wp_memory_limit: 96M
      wp_max_memory_limit: "{{ php_memory_limit }}"
